<a href="https://colab.research.google.com/github/Janevein/PythonProgramming/blob/main/talkative_game_khaing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

def initialize_classroom(class_size, classroom_size):
    green_dots = np.random.rand(class_size, 2) * classroom_size
    talkative_student = np.random.random((1, 2)) * classroom_size
    students = np.vstack([green_dots, talkative_student])
    return students

def infect_student(students, infected_students, talkative_student_index):
    available_green_dots = np.delete(np.arange(len(students) - 1), list(infected_students))
    infected_student = random.choice(available_green_dots)
    students[infected_student] = students[talkative_student_index]
    print(f"Green dot {infected_student} infected by talkative student.")
    infected_students.add(infected_student)

def play_classroom_simulation(total_iterations, class_size=11, classroom_size=20,
                               distance_threshold=2, max_attempts=5,
                               teacher_warnings_interval=5,
                               kick_out_interval=10,
                               infections_allowed_after_kick_out=2):
    students = initialize_classroom(class_size, classroom_size)
    teacher_warnings = 0
    teacher_warnings_interval = 5
    iterations = 0
    infected_students = set()

    while iterations < total_iterations:
        print(f"\nIteration {iterations + 1}")
        print("Student Positions:")
        print(students)

        if iterations % teacher_warnings_interval == 0:
            if random.choice([True, False]): # Randomly select who gets the warning
                if teacher_warnings == 0:
                    print("Teacher Warning: Quiet down, students!")
                elif teacher_warnings == 1:
                    print("Teacher Warning: Last warning! Next time you're out of the class.")
                else:
                    print("Teacher: That's enough! You're out of the class.")
                    for _ in range(infections_allowed_after_kick_out):
                        infect_student(students, infected_students, len(students) - 1)
                    teacher_warnings = 0

                teacher_warnings += 1

            else: # Talkative student gets the warning
                if teacher_warnings == 0:
                    print("Talkative Student Warning: Quiet down!")
                elif teacher_warnings == 1:
                    print("Talkative Student Warning: Last warning! Next time you're out of the class.")
                else:
                    print("Talkative Student: That's enough! I'm out of the class.")
                    for _ in range(infections_allowed_after_kick_out):
                        infect_student(students, infected_students, class_size)
                teacher_warnings = 0

                teacher_warnings += 1

        students -= (0.005 * students)
        students = np.clip(students, 0, classroom_size)
        iterations += 1

        if iterations == total_iterations:
            remaining_students = np.unique(students, axis=0)
            if len(remaining_students) == 1:
                print("Teacher Wins! One student is still in the class.")
            else:
                print("Students Win! They all are now out of the class")
            break

# Play the classroom simulation for a total of 60 iterations
play_classroom_simulation(total_iterations=60)


Iteration 1
Student Positions:
[[19.21812864 11.69602487]
 [17.88640029  5.07668727]
 [ 0.911288   10.11260611]
 [19.1305394   2.19714717]
 [ 7.51647055 13.29107575]
 [ 2.62325968  3.71227668]
 [ 6.51001021 11.91973715]
 [11.78569992 14.53196556]
 [15.58161819  8.12486627]
 [ 4.59883975  9.64811789]
 [14.99194732  3.56847429]
 [10.59262133 18.12627735]]
Talkative Student Warning: Quiet down!

Iteration 2
Student Positions:
[[19.12203799 11.63754475]
 [17.79696829  5.05130383]
 [ 0.90673156 10.06204308]
 [19.0348867   2.18616144]
 [ 7.4788882  13.22462037]
 [ 2.61014338  3.69371529]
 [ 6.47746016 11.86013846]
 [11.72677142 14.45930573]
 [15.5037101   8.08424194]
 [ 4.57584555  9.5998773 ]
 [14.91698758  3.55063192]
 [10.53965822 18.03564597]]

Iteration 3
Student Positions:
[[19.0264278  11.57935703]
 [17.70798345  5.02604731]
 [ 0.9021979  10.01173286]
 [18.93971227  2.17523063]
 [ 7.44149376 13.15849727]
 [ 2.59709267  3.67524672]
 [ 6.44507286 11.80083777]
 [11.66813756 14.3870092 ]

In [2]:
import numpy as np
import random

def initialize_classroom(class_size, classroom_size):
    green_dots = np.random.rand(class_size, 2) * classroom_size
    talkative_student = np.random.random((1, 2)) * classroom_size
    students = np.vstack([green_dots, talkative_student])
    return students

def infect_student(students, infected_students, talkative_student_index):
    available_green_dots = np.delete(np.arange(len(students) - 1), list(infected_students))
    infected_student = random.choice(available_green_dots)
    students[infected_student] = students[talkative_student_index]
    print(f"Green dot {infected_student} infected by talkative student.")
    infected_students.add(infected_student)

def play_classroom_simulation(total_iterations, class_size=11, classroom_size=20,
                               distance_threshold=2, max_attempts=5,
                               teacher_warnings_interval=5,
                               kick_out_interval=10,
                               infections_allowed_after_kick_out=2):
    students = initialize_classroom(class_size, classroom_size)
    teacher_warnings = 0
    iterations = 0
    infected_students = set()

    while iterations < total_iterations:
        print(f"\nIteration {iterations + 1}")
        print("Student Positions:")
        print(students)

        if iterations % teacher_warnings_interval == 0:
            if random.choice([True, False]): # Randomly select who gets the warning
                if teacher_warnings == 0:
                    print("Teacher Warning: Quiet down, students!")
                elif teacher_warnings == 1:
                    print("Teacher Warning: Last warning! Next time you're out of the class.")
                else:
                    print("Teacher: That's enough! You're out of the class.")
                    for _ in range(infections_allowed_after_kick_out):
                        infect_student(students, infected_students, len(students) - 1)
                    teacher_warnings = 0

                teacher_warnings += 1

            else: # Talkative student gets the warning
                if teacher_warnings == 0:
                    print("Talkative Student Warning: Quiet down!")
                elif teacher_warnings == 1:
                    print("Talkative Student Warning: Last warning! Next time you're out of the class.")
                else:
                    print("Talkative Student: That's enough! I'm out of the class.")
                    for _ in range(infections_allowed_after_kick_out):
                        infect_student(students, infected_students, class_size)
                    teacher_warnings = 0

                teacher_warnings += 1

        students += (0.05 * students)
        students = np.clip(students, 0, classroom_size)
        iterations += 1

        if iterations == total_iterations:
            remaining_students = np.unique(students, axis=0)
            if len(remaining_students) == 1:
                print("Teacher Wins! One student is still in the class.")
            else:
                print("Students Win! They all are now out of the class")
            break

# Play the classroom simulation for a total of 60 iterations
play_classroom_simulation(total_iterations=60)


Iteration 1
Student Positions:
[[12.59304188  3.9233601 ]
 [10.1305452   7.69736889]
 [ 0.9055416  13.35938083]
 [18.5981618   8.62682378]
 [ 8.29218974 15.14232729]
 [17.04808546 16.79592065]
 [ 7.12825671  4.59534386]
 [18.9355167  10.83581203]
 [15.15625062  5.48067667]
 [ 0.74665046  4.17797236]
 [12.70931175  6.82979398]
 [14.07767503 12.49201139]]
Teacher Warning: Quiet down, students!

Iteration 2
Student Positions:
[[13.22269397  4.11952811]
 [10.63707246  8.08223733]
 [ 0.95081868 14.02734987]
 [19.52806989  9.05816496]
 [ 8.70679922 15.89944366]
 [17.90048973 17.63571669]
 [ 7.48466954  4.82511105]
 [19.88229254 11.37760263]
 [15.91406315  5.75471051]
 [ 0.78398298  4.38687098]
 [13.34477734  7.17128367]
 [14.78155878 13.11661196]]

Iteration 3
Student Positions:
[[13.88382867  4.32550451]
 [11.16892608  8.4863492 ]
 [ 0.99835961 14.72871736]
 [20.          9.51107321]
 [ 9.14213918 16.69441584]
 [18.79551422 18.51750252]
 [ 7.85890302  5.0663666 ]
 [20.         11.94648277]